In [25]:
import cv2
import os
import numpy as np
import matplotlib.pyplot as plt
from ultralytics import YOLO
from keras.models import Sequential, model_from_json, load_model
import glob
import time

In [26]:
def mass_center(img,is_round=True):
    Y = img.mean(axis=1)
    X = img.mean(axis=0)
    Y_ = np.sum(np.arange(Y.shape[0]) * Y)/np.sum(Y)
    X_ = np.sum(np.arange(X.shape[0]) * X)/np.sum(X)
    if is_round:
        return int(round(X_)),int(round(Y_))
    return X_,Y_

def image_extract(img,newsize):
    if (len(np.where(img.mean(axis=0)!=0)[0]) != 0):
        x_s = np.where(img.mean(axis=0)!=0)[0].min()
        x_e = np.where(img.mean(axis=0)!=0)[0].max()
        
        y_s = np.where(img.mean(axis=1)!=0)[0].min()
        y_e = np.where(img.mean(axis=1)!=0)[0].max()
        
        x_c,_ = mass_center(img)
        x_s = x_c-newsize[1]//2
        x_e = x_c+newsize[1]//2
        img = img[y_s:y_e,x_s if x_s>0 else 0:x_e if x_e<img.shape[1] else img.shape[1]]
        return cv2.resize(img,newsize)
    else:
        return 0

In [27]:
lables = {'Abhirami': 0,
            'Aswathy': 1,
            'Ayana': 2,
            'Lekshmi': 3,
            'Nandana': 4,
            'Parthiv': 5,
            'Shilpa': 6,}

In [28]:
vid_file = './dataset/parthiv/15.mp4'

vidcap = cv2.VideoCapture(vid_file)
length = int(vidcap.get(cv2.CAP_PROP_FRAME_COUNT))
success,image = vidcap.read()
count = 0
mask_count = 0
thresh = 127
message = 'Analyzing...'
m2 = ' '
fps = 0

pretrained_weight = './yolov8x-seg.pt'
model = YOLO(pretrained_weight)
new_model = load_model('./fine_tuned.h5')

mask_dir = './output/masks/'
mask_files = glob.glob(mask_dir+ '/*')
for f in mask_files:
    os.remove(f)

while success:
    start = time.time()
    if(count%4 == 0):
        results = model(image)
        masks = results[0].masks
        if masks:
            m2 = 'YOLO v8 = Inference: {0} ms | Preprocess: {1} ms | Postprocess: {2} ms' .format(round(results[0].speed['inference'], 2), round(results[0].speed['preprocess'], 2), round(results[0].speed['postprocess'], 2))
            mask_count = mask_count+1
            ms = masks.data.numpy()
            cv2.imwrite(mask_dir + str(count) + '.png', ms[0,:,:]*255)
        
    if(mask_count >= 10):
        image_data = []
        files = os.listdir('./output/masks/')
        for f in files:
            im = cv2.imread('./output/masks/'+'/'+f, 0)
            im_bw = cv2.threshold(im, thresh, 255, cv2.THRESH_BINARY)[1]
            item = image_extract(im_bw, (64, 128))
            if(np.max(item) != 0):
                image_data.append(item)
        gei = np.mean(image_data,axis=0)

        res_img = cv2.resize(gei, (224,224))
        test_img = cv2.merge([res_img, res_img, res_img])
        test_img = test_img/255
        test_img = np.reshape(test_img, (1, 224, 224, 3))
        
        preds = new_model.predict(test_img)
        print(preds)
        prediction = np.argmax(preds)
        print(prediction)
        for name, label in lables.items():
            if label == prediction:
                message = 'Detected : ' + name + ' (' + str(round(preds[0][prediction]*100, 2)) + '% Accuracy)'

    success,image = vidcap.read()
    count += 1

    mask_out = cv2.merge([ms[0,:,:]*255, ms[0,:,:]*255, ms[0,:,:]*255])

    font = cv2.FONT_HERSHEY_SIMPLEX
    org = (25, 35)
    org1 = (25, 60)
    org2 = (25, 330)
    org3 = (495, 330)
    fontScale = 0.8
    fontScale2 = 0.45
    fontScale3 = 0.65
    color = (0, 0, 0)
    color2 = (0, 0, 255)
    color3 = (255, 255, 255)
    color4 = (255, 0, 255)
    color5 = (0, 255, 0)
    thickness = 2
    thickness2 = 1

    title1 = 'Live'
    org4 = (25, 30)
    title2 = 'YOLO v8 generated mask'

    fps_msg = 'FPS: ' + str(round(fps/1000, 2))
    image = cv2.putText(image, fps_msg, org3, font, 
                   fontScale3, color2, thickness, cv2.LINE_AA)
    image = cv2.putText(image, title1, org4, font, 
                   fontScale3, color2, thickness, cv2.LINE_AA)
        
    mask_out = cv2.putText(mask_out, title2, org4, font, 
                   fontScale3, color4, thickness, cv2.LINE_AA)
    
    # mask_out = cv2.putText(mask_out, m2, org2, font, 
    #                 fontScale2, color5, thickness2, cv2.LINE_AA)
    
    prompt = np.zeros((95, 640, 3))*255
    prompt = cv2.putText(prompt, message, org, font, 
                    fontScale, color5, thickness, cv2.LINE_AA)
    prompt = cv2.putText(prompt, m2, org1, font, 
                    fontScale2, color3, thickness2, cv2.LINE_AA)
    if(image is None):
        cv2.destroyAllWindows()
    if(image is not None):
        # cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)/255
        disp = np.concatenate((cv2.resize(image/255, (640, 280)), cv2.resize(mask_out, (640, 280))), axis=0)
        info = np.concatenate((disp, prompt), axis=0)
        cv2.imshow('Live', info)
        key = cv2.waitKey(1)
        if key == 27:
            cv2.destroyAllWindows()
            break
    end = time.time()
    seconds = end - start 
    fps  = length / seconds


0: 352x640 1 person, 1 book, 728.4ms
Speed: 2.0ms preprocess, 728.4ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 352x640 1 person, 1 cell phone, 703.6ms
Speed: 0.0ms preprocess, 703.6ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 352x640 1 person, 690.6ms
Speed: 1.0ms preprocess, 690.6ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 640)

0: 352x640 1 person, 710.0ms
Speed: 1.0ms preprocess, 710.0ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)

0: 352x640 1 person, 730.4ms
Speed: 1.0ms preprocess, 730.4ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)

0: 352x640 1 person, 712.8ms
Speed: 2.0ms preprocess, 712.8ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)

0: 352x640 1 person, 751.2ms
Speed: 2.0ms preprocess, 751.2ms inference, 4.1ms postprocess per image at shape (1, 3, 640, 640)

0: 352x640 1 person, 749.4ms
Speed: 1.0ms preprocess, 749.4ms inference, 4.0ms po

1/1 [==============================] - 1s 759ms/step
[[ 3.9384e-11  1.1175e-09  8.8894e-10  8.1535e-16     0.99997  1.1185e-05  1.8743e-05]]
4
1/1 [==============================] - 0s 22ms/step
[[ 3.9384e-11  1.1175e-09  8.8894e-10  8.1535e-16     0.99997  1.1185e-05  1.8743e-05]]
4
1/1 [==============================] - 0s 35ms/step
[[ 3.9384e-11  1.1175e-09  8.8894e-10  8.1535e-16     0.99997  1.1185e-05  1.8743e-05]]
4
1/1 [==============================] - 0s 21ms/step


[[ 3.9384e-11  1.1175e-09  8.8894e-10  8.1535e-16     0.99997  1.1185e-05  1.8743e-05]]
4


0: 352x640 1 person, 728.6ms
Speed: 2.0ms preprocess, 728.6ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 23ms/step
[[ 1.5201e-11  5.4221e-10  1.8546e-09  4.6115e-16     0.99998  4.9146e-06  1.0759e-05]]
4
1/1 [==============================] - 0s 29ms/step
[[ 1.5201e-11  5.4221e-10  1.8546e-09  4.6115e-16     0.99998  4.9146e-06  1.0759e-05]]
4
1/1 [==============================] - 0s 35ms/step
[[ 1.5201e-11  5.4221e-10  1.8546e-09  4.6115e-16     0.99998  4.9146e-06  1.0759e-05]]
4
1/1 [==============================] - 0s 18ms/step


[[ 1.5201e-11  5.4221e-10  1.8546e-09  4.6115e-16     0.99998  4.9146e-06  1.0759e-05]]
4


0: 352x640 1 person, 737.5ms
Speed: 1.0ms preprocess, 737.5ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 21ms/step
[[ 1.0169e-11  5.6804e-10  2.4725e-09  2.4252e-16     0.99997  6.2717e-06  2.0201e-05]]
4
1/1 [==============================] - 0s 22ms/step
[[ 1.0169e-11  5.6804e-10  2.4725e-09  2.4252e-16     0.99997  6.2717e-06  2.0201e-05]]
4
1/1 [==============================] - 0s 20ms/step
[[ 1.0169e-11  5.6804e-10  2.4725e-09  2.4252e-16     0.99997  6.2717e-06  2.0201e-05]]
4
1/1 [==============================] - 0s 20ms/step


[[ 1.0169e-11  5.6804e-10  2.4725e-09  2.4252e-16     0.99997  6.2717e-06  2.0201e-05]]
4


0: 352x640 1 person, 734.4ms
Speed: 1.0ms preprocess, 734.4ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 20ms/step
[[ 8.6015e-12  4.2649e-09  1.9725e-09  2.9933e-16     0.99995  4.3277e-06  4.8409e-05]]
4
1/1 [==============================] - 0s 21ms/step
[[ 8.6015e-12  4.2649e-09  1.9725e-09  2.9933e-16     0.99995  4.3277e-06  4.8409e-05]]
4
1/1 [==============================] - 0s 38ms/step
[[ 8.6015e-12  4.2649e-09  1.9725e-09  2.9933e-16     0.99995  4.3277e-06  4.8409e-05]]
4
1/1 [==============================] - 0s 23ms/step


[[ 8.6015e-12  4.2649e-09  1.9725e-09  2.9933e-16     0.99995  4.3277e-06  4.8409e-05]]
4


0: 352x640 1 person, 708.1ms
Speed: 1.0ms preprocess, 708.1ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 21ms/step
[[ 6.0871e-12  6.9213e-09  2.2185e-09  1.2918e-16     0.99992  6.7385e-06   7.522e-05]]
4
1/1 [==============================] - 0s 20ms/step
[[ 6.0871e-12  6.9213e-09  2.2185e-09  1.2918e-16     0.99992  6.7385e-06   7.522e-05]]
4
1/1 [==============================] - 0s 23ms/step
[[ 6.0871e-12  6.9213e-09  2.2185e-09  1.2918e-16     0.99992  6.7385e-06   7.522e-05]]
4
1/1 [==============================] - 0s 21ms/step


[[ 6.0871e-12  6.9213e-09  2.2185e-09  1.2918e-16     0.99992  6.7385e-06   7.522e-05]]
4


0: 352x640 1 person, 722.2ms
Speed: 1.0ms preprocess, 722.2ms inference, 3.7ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 25ms/step
[[ 4.9502e-12  5.3456e-09  3.4796e-09  1.1684e-16      0.9998  1.7645e-05  0.00017972]]
4
1/1 [==============================] - 0s 26ms/step
[[ 4.9502e-12  5.3456e-09  3.4796e-09  1.1684e-16      0.9998  1.7645e-05  0.00017972]]
4
1/1 [==============================] - 0s 21ms/step
[[ 4.9502e-12  5.3456e-09  3.4796e-09  1.1684e-16      0.9998  1.7645e-05  0.00017972]]
4
1/1 [==============================] - 0s 20ms/step


[[ 4.9502e-12  5.3456e-09  3.4796e-09  1.1684e-16      0.9998  1.7645e-05  0.00017972]]
4


0: 352x640 1 person, 774.8ms
Speed: 1.6ms preprocess, 774.8ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 21ms/step
[[  7.361e-12  5.9997e-09  2.6927e-09  1.5957e-16     0.99911  5.2779e-05  0.00083379]]
4
1/1 [==============================] - 0s 19ms/step
[[  7.361e-12  5.9997e-09  2.6927e-09  1.5957e-16     0.99911  5.2779e-05  0.00083379]]
4
1/1 [==============================] - 0s 21ms/step
[[  7.361e-12  5.9997e-09  2.6927e-09  1.5957e-16     0.99911  5.2779e-05  0.00083379]]
4
1/1 [==============================] - 0s 20ms/step


[[  7.361e-12  5.9997e-09  2.6927e-09  1.5957e-16     0.99911  5.2779e-05  0.00083379]]
4


0: 352x640 1 person, 689.6ms
Speed: 1.0ms preprocess, 689.6ms inference, 4.1ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 19ms/step
[[ 6.4055e-12   5.105e-09   3.872e-09  2.1078e-16     0.99744  0.00018684   0.0023695]]
4
1/1 [==============================] - 0s 22ms/step
[[ 6.4055e-12   5.105e-09   3.872e-09  2.1078e-16     0.99744  0.00018684   0.0023695]]
4
1/1 [==============================] - 0s 22ms/step
[[ 6.4055e-12   5.105e-09   3.872e-09  2.1078e-16     0.99744  0.00018684   0.0023695]]
4
1/1 [==============================] - 0s 28ms/step


[[ 6.4055e-12   5.105e-09   3.872e-09  2.1078e-16     0.99744  0.00018684   0.0023695]]
4


0: 352x640 1 person, 693.5ms
Speed: 0.0ms preprocess, 693.5ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 27ms/step
[[ 1.3066e-11  9.0049e-09  7.1285e-09  3.4941e-16     0.99379  0.00047051   0.0057361]]
4
1/1 [==============================] - 0s 29ms/step
[[ 1.3066e-11  9.0049e-09  7.1285e-09  3.4941e-16     0.99379  0.00047051   0.0057361]]
4
1/1 [==============================] - 0s 24ms/step
[[ 1.3066e-11  9.0049e-09  7.1285e-09  3.4941e-16     0.99379  0.00047051   0.0057361]]
4
1/1 [==============================] - 0s 23ms/step


[[ 1.3066e-11  9.0049e-09  7.1285e-09  3.4941e-16     0.99379  0.00047051   0.0057361]]
4


0: 352x640 1 person, 704.5ms
Speed: 1.0ms preprocess, 704.5ms inference, 4.1ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 20ms/step
[[ 1.1318e-11  7.7958e-09  7.9882e-09  2.8553e-16     0.98977  0.00087977   0.0093453]]
4
1/1 [==============================] - 0s 21ms/step
[[ 1.1318e-11  7.7958e-09  7.9882e-09  2.8553e-16     0.98977  0.00087977   0.0093453]]
4
1/1 [==============================] - 0s 21ms/step
[[ 1.1318e-11  7.7958e-09  7.9882e-09  2.8553e-16     0.98977  0.00087977   0.0093453]]
4
1/1 [==============================] - 0s 20ms/step


[[ 1.1318e-11  7.7958e-09  7.9882e-09  2.8553e-16     0.98977  0.00087977   0.0093453]]
4


0: 352x640 1 person, 694.7ms
Speed: 1.0ms preprocess, 694.7ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 21ms/step
[[ 9.2741e-12  4.9062e-09  6.6568e-09  2.1922e-16     0.98937   0.0010592   0.0095727]]
4
1/1 [==============================] - 0s 20ms/step
[[ 9.2741e-12  4.9062e-09  6.6568e-09  2.1922e-16     0.98937   0.0010592   0.0095727]]
4
1/1 [==============================] - 0s 20ms/step
[[ 9.2741e-12  4.9062e-09  6.6568e-09  2.1922e-16     0.98937   0.0010592   0.0095727]]
4
1/1 [==============================] - 0s 20ms/step


[[ 9.2741e-12  4.9062e-09  6.6568e-09  2.1922e-16     0.98937   0.0010592   0.0095727]]
4


0: 352x640 1 person, 687.3ms
Speed: 0.0ms preprocess, 687.3ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 20ms/step
[[ 1.1455e-11  3.1898e-09  6.3185e-09  2.9485e-16      0.9907   0.0013129    0.007992]]
4
1/1 [==============================] - 0s 19ms/step
[[ 1.1455e-11  3.1898e-09  6.3185e-09  2.9485e-16      0.9907   0.0013129    0.007992]]
4
1/1 [==============================] - 0s 20ms/step
[[ 1.1455e-11  3.1898e-09  6.3185e-09  2.9485e-16      0.9907   0.0013129    0.007992]]
4
1/1 [==============================] - 0s 19ms/step


[[ 1.1455e-11  3.1898e-09  6.3185e-09  2.9485e-16      0.9907   0.0013129    0.007992]]
4


0: 352x640 1 person, 697.0ms
Speed: 1.0ms preprocess, 697.0ms inference, 4.1ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 21ms/step
[[ 6.4519e-12  8.8323e-09  1.2422e-08  2.2807e-16     0.99072   0.0027544    0.006521]]
4
1/1 [==============================] - 0s 25ms/step
[[ 6.4519e-12  8.8323e-09  1.2422e-08  2.2807e-16     0.99072   0.0027544    0.006521]]
4
1/1 [==============================] - 0s 21ms/step
[[ 6.4519e-12  8.8323e-09  1.2422e-08  2.2807e-16     0.99072   0.0027544    0.006521]]
4
1/1 [==============================] - 0s 20ms/step
[[ 6.4519e-12  8.8323e-09  1.2422e-08  2.2807e-16     0.99072   0.0027544    0.006521]]
4



0: 352x640 1 person, 697.2ms
Speed: 1.0ms preprocess, 697.2ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 21ms/step
[[ 3.3988e-14  5.5535e-11  2.2098e-09  9.4914e-19     0.99993  4.3611e-05  2.6685e-05]]
4
1/1 [==============================] - 0s 22ms/step
[[ 3.3988e-14  5.5535e-11  2.2098e-09  9.4914e-19     0.99993  4.3611e-05  2.6685e-05]]
4
1/1 [==============================] - 0s 20ms/step
[[ 3.3988e-14  5.5535e-11  2.2098e-09  9.4914e-19     0.99993  4.3611e-05  2.6685e-05]]
4
1/1 [==============================] - 0s 21ms/step


[[ 3.3988e-14  5.5535e-11  2.2098e-09  9.4914e-19     0.99993  4.3611e-05  2.6685e-05]]
4


0: 352x640 1 person, 728.8ms
Speed: 1.0ms preprocess, 728.8ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 20ms/step
[[ 6.2787e-14  4.1949e-11  3.0026e-09  2.6422e-18     0.99997  1.4947e-05  1.9425e-05]]
4
1/1 [==============================] - 0s 20ms/step
[[ 6.2787e-14  4.1949e-11  3.0026e-09  2.6422e-18     0.99997  1.4947e-05  1.9425e-05]]
4
1/1 [==============================] - 0s 30ms/step
[[ 6.2787e-14  4.1949e-11  3.0026e-09  2.6422e-18     0.99997  1.4947e-05  1.9425e-05]]
4
1/1 [==============================] - 0s 21ms/step


[[ 6.2787e-14  4.1949e-11  3.0026e-09  2.6422e-18     0.99997  1.4947e-05  1.9425e-05]]
4


0: 352x640 1 person, 701.2ms
Speed: 1.2ms preprocess, 701.2ms inference, 4.3ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 20ms/step
[[  8.253e-14  3.9385e-10  3.2139e-09  2.8663e-17     0.99982  2.6613e-05  0.00015663]]
4
1/1 [==============================] - 0s 36ms/step
[[  8.253e-14  3.9385e-10  3.2139e-09  2.8663e-17     0.99982  2.6613e-05  0.00015663]]
4
1/1 [==============================] - 0s 21ms/step
[[  8.253e-14  3.9385e-10  3.2139e-09  2.8663e-17     0.99982  2.6613e-05  0.00015663]]
4
1/1 [==============================] - 0s 21ms/step


[[  8.253e-14  3.9385e-10  3.2139e-09  2.8663e-17     0.99982  2.6613e-05  0.00015663]]
4


0: 352x640 1 person, 691.2ms
Speed: 1.0ms preprocess, 691.2ms inference, 6.5ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 35ms/step
[[  9.083e-14  1.7032e-10  1.4668e-09  2.9797e-17     0.99991   2.916e-05  5.7708e-05]]
4
1/1 [==============================] - 0s 20ms/step
[[  9.083e-14  1.7032e-10  1.4668e-09  2.9797e-17     0.99991   2.916e-05  5.7708e-05]]
4
1/1 [==============================] - 0s 22ms/step
[[  9.083e-14  1.7032e-10  1.4668e-09  2.9797e-17     0.99991   2.916e-05  5.7708e-05]]
4
1/1 [==============================] - 0s 20ms/step


[[  9.083e-14  1.7032e-10  1.4668e-09  2.9797e-17     0.99991   2.916e-05  5.7708e-05]]
4


0: 352x640 1 person, 716.5ms
Speed: 0.0ms preprocess, 716.5ms inference, 4.4ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 20ms/step
[[  7.856e-14  2.9916e-10  8.3728e-10  2.3248e-18     0.99836  0.00043744   0.0011982]]
4
1/1 [==============================] - 0s 35ms/step
[[  7.856e-14  2.9916e-10  8.3728e-10  2.3248e-18     0.99836  0.00043744   0.0011982]]
4
1/1 [==============================] - 0s 21ms/step
[[  7.856e-14  2.9916e-10  8.3728e-10  2.3248e-18     0.99836  0.00043744   0.0011982]]
4
1/1 [==============================] - 0s 37ms/step
[[  7.856e-14  2.9916e-10  8.3728e-10  2.3248e-18     0.99836  0.00043744   0.0011982]]
4



0: 352x640 1 person, 726.9ms
Speed: 2.0ms preprocess, 726.9ms inference, 4.1ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 26ms/step
[[ 9.7903e-12  2.4141e-08  8.4312e-10  2.5323e-18     0.99474   0.0039551   0.0013066]]
4
1/1 [==============================] - 0s 21ms/step
[[ 9.7903e-12  2.4141e-08  8.4312e-10  2.5323e-18     0.99474   0.0039551   0.0013066]]
4
1/1 [==============================] - 0s 22ms/step
[[ 9.7903e-12  2.4141e-08  8.4312e-10  2.5323e-18     0.99474   0.0039551   0.0013066]]
4
1/1 [==============================] - 0s 21ms/step
[[ 9.7903e-12  2.4141e-08  8.4312e-10  2.5323e-18     0.99474   0.0039551   0.0013066]]
4



0: 352x640 1 person, 726.6ms
Speed: 1.0ms preprocess, 726.6ms inference, 4.1ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 19ms/step
[[ 8.4313e-11  3.3842e-08  7.5345e-09  2.1825e-17     0.73611     0.23752    0.026364]]
4
1/1 [==============================] - 0s 20ms/step
[[ 8.4313e-11  3.3842e-08  7.5345e-09  2.1825e-17     0.73611     0.23752    0.026364]]
4
1/1 [==============================] - 0s 20ms/step
[[ 8.4313e-11  3.3842e-08  7.5345e-09  2.1825e-17     0.73611     0.23752    0.026364]]
4
1/1 [==============================] - 0s 22ms/step
[[ 8.4313e-11  3.3842e-08  7.5345e-09  2.1825e-17     0.73611     0.23752    0.026364]]
4



0: 352x640 1 person, 750.6ms
Speed: 1.0ms preprocess, 750.6ms inference, 4.5ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 20ms/step
[[ 8.6177e-11  1.3285e-08  2.2127e-09  8.0305e-18     0.63649     0.35662   0.0068969]]
4
1/1 [==============================] - 0s 22ms/step
[[ 8.6177e-11  1.3285e-08  2.2127e-09  8.0305e-18     0.63649     0.35662   0.0068969]]
4
1/1 [==============================] - 0s 22ms/step
[[ 8.6177e-11  1.3285e-08  2.2127e-09  8.0305e-18     0.63649     0.35662   0.0068969]]
4
1/1 [==============================] - 0s 24ms/step


[[ 8.6177e-11  1.3285e-08  2.2127e-09  8.0305e-18     0.63649     0.35662   0.0068969]]
4


0: 352x640 1 person, 712.3ms
Speed: 0.9ms preprocess, 712.3ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 19ms/step
[[ 8.7821e-11   4.494e-09  2.8185e-10   4.255e-18     0.15806     0.83568   0.0062594]]
5
1/1 [==============================] - 0s 30ms/step
[[ 8.7821e-11   4.494e-09  2.8185e-10   4.255e-18     0.15806     0.83568   0.0062594]]
5
1/1 [==============================] - 0s 21ms/step
[[ 8.7821e-11   4.494e-09  2.8185e-10   4.255e-18     0.15806     0.83568   0.0062594]]
5
1/1 [==============================] - 0s 20ms/step
[[ 8.7821e-11   4.494e-09  2.8185e-10   4.255e-18     0.15806     0.83568   0.0062594]]
5



0: 352x640 1 person, 709.9ms
Speed: 2.0ms preprocess, 709.9ms inference, 4.4ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 20ms/step
[[  2.346e-11  8.4642e-09  2.8898e-11  1.0704e-18    0.061955     0.91381     0.02423]]
5
1/1 [==============================] - 0s 21ms/step
[[  2.346e-11  8.4642e-09  2.8898e-11  1.0704e-18    0.061955     0.91381     0.02423]]
5
1/1 [==============================] - 0s 9ms/step
[[  2.346e-11  8.4642e-09  2.8898e-11  1.0704e-18    0.061955     0.91381     0.02423]]
5
1/1 [==============================] - 0s 29ms/step


[[  2.346e-11  8.4642e-09  2.8898e-11  1.0704e-18    0.061955     0.91381     0.02423]]
5


0: 352x640 1 person, 715.1ms
Speed: 2.0ms preprocess, 715.1ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 21ms/step
[[ 3.4358e-11  8.2843e-09  1.0466e-10  2.6137e-18     0.08104     0.88441    0.034546]]
5
1/1 [==============================] - 0s 21ms/step
[[ 3.4358e-11  8.2843e-09  1.0466e-10  2.6137e-18     0.08104     0.88441    0.034546]]
5
1/1 [==============================] - 0s 23ms/step
[[ 3.4358e-11  8.2843e-09  1.0466e-10  2.6137e-18     0.08104     0.88441    0.034546]]
5
1/1 [==============================] - 0s 20ms/step
[[ 3.4358e-11  8.2843e-09  1.0466e-10  2.6137e-18     0.08104     0.88441    0.034546]]
5



0: 352x640 1 person, 743.3ms
Speed: 0.0ms preprocess, 743.3ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 20ms/step
[[ 9.0615e-11  5.5554e-09  2.6897e-10  6.3819e-18     0.31731     0.63716    0.045532]]
5
1/1 [==============================] - 0s 23ms/step
[[ 9.0615e-11  5.5554e-09  2.6897e-10  6.3819e-18     0.31731     0.63716    0.045532]]
5
1/1 [==============================] - 0s 20ms/step
[[ 9.0615e-11  5.5554e-09  2.6897e-10  6.3819e-18     0.31731     0.63716    0.045532]]
5
1/1 [==============================] - 0s 28ms/step


[[ 9.0615e-11  5.5554e-09  2.6897e-10  6.3819e-18     0.31731     0.63716    0.045532]]
5


0: 352x640 1 person, 709.7ms
Speed: 1.0ms preprocess, 709.7ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 33ms/step
[[ 1.1057e-10  2.1941e-09   1.389e-10  8.6892e-18     0.17309     0.72151      0.1054]]
5
1/1 [==============================] - 0s 23ms/step
[[ 1.1057e-10  2.1941e-09   1.389e-10  8.6892e-18     0.17309     0.72151      0.1054]]
5
1/1 [==============================] - 0s 26ms/step
[[ 1.1057e-10  2.1941e-09   1.389e-10  8.6892e-18     0.17309     0.72151      0.1054]]
5
1/1 [==============================] - 0s 21ms/step


[[ 1.1057e-10  2.1941e-09   1.389e-10  8.6892e-18     0.17309     0.72151      0.1054]]
5


0: 352x640 1 person, 759.7ms
Speed: 1.0ms preprocess, 759.7ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 23ms/step
[[ 5.1877e-11  9.2598e-10  8.0133e-11  4.4109e-18     0.14794      0.7767    0.075359]]
5
1/1 [==============================] - 0s 22ms/step
[[ 5.1877e-11  9.2598e-10  8.0133e-11  4.4109e-18     0.14794      0.7767    0.075359]]
5
1/1 [==============================] - 0s 36ms/step
[[ 5.1877e-11  9.2598e-10  8.0133e-11  4.4109e-18     0.14794      0.7767    0.075359]]
5
1/1 [==============================] - 0s 21ms/step
[[ 5.1877e-11  9.2598e-10  8.0133e-11  4.4109e-18     0.14794      0.7767    0.075359]]
5



0: 352x640 1 person, 698.8ms
Speed: 1.0ms preprocess, 698.8ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 37ms/step
[[ 3.4785e-11  5.0391e-10  1.0174e-10  3.0098e-18     0.13941     0.79865    0.061934]]
5
1/1 [==============================] - 0s 20ms/step
[[ 3.4785e-11  5.0391e-10  1.0174e-10  3.0098e-18     0.13941     0.79865    0.061934]]
5
1/1 [==============================] - 0s 23ms/step
[[ 3.4785e-11  5.0391e-10  1.0174e-10  3.0098e-18     0.13941     0.79865    0.061934]]
5
1/1 [==============================] - 0s 21ms/step
[[ 3.4785e-11  5.0391e-10  1.0174e-10  3.0098e-18     0.13941     0.79865    0.061934]]


5


0: 352x640 1 person, 712.4ms
Speed: 1.0ms preprocess, 712.4ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 20ms/step
[[ 5.7724e-11  2.2079e-10   7.328e-11  6.4988e-19    0.019575     0.95491    0.025519]]
5
1/1 [==============================] - 0s 19ms/step
[[ 5.7724e-11  2.2079e-10   7.328e-11  6.4988e-19    0.019575     0.95491    0.025519]]
5
1/1 [==============================] - 0s 19ms/step
[[ 5.7724e-11  2.2079e-10   7.328e-11  6.4988e-19    0.019575     0.95491    0.025519]]
5
1/1 [==============================] - 0s 25ms/step
[[ 5.7724e-11  2.2079e-10   7.328e-11  6.4988e-19    0.019575     0.95491    0.025519]]
5



0: 352x640 1 person, 1 refrigerator, 693.3ms
Speed: 0.9ms preprocess, 693.3ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 36ms/step
[[ 1.2857e-11  2.0861e-10  2.7345e-11  1.6185e-19   0.0045674     0.95228    0.043151]]
5
1/1 [==============================] - 0s 25ms/step
[[ 1.2857e-11  2.0861e-10  2.7345e-11  1.6185e-19   0.0045674     0.95228    0.043151]]
5
1/1 [==============================] - 0s 22ms/step
[[ 1.2857e-11  2.0861e-10  2.7345e-11  1.6185e-19   0.0045674     0.95228    0.043151]]
5
1/1 [==============================] - 0s 35ms/step


[[ 1.2857e-11  2.0861e-10  2.7345e-11  1.6185e-19   0.0045674     0.95228    0.043151]]
5


0: 352x640 1 person, 698.0ms
Speed: 0.9ms preprocess, 698.0ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 21ms/step
[[ 2.3006e-12  1.2845e-11  2.7819e-11  3.4609e-20    0.001702     0.96309    0.035211]]
5
1/1 [==============================] - 0s 38ms/step
[[ 2.3006e-12  1.2845e-11  2.7819e-11  3.4609e-20    0.001702     0.96309    0.035211]]
5
1/1 [==============================] - 0s 20ms/step
[[ 2.3006e-12  1.2845e-11  2.7819e-11  3.4609e-20    0.001702     0.96309    0.035211]]
5
1/1 [==============================] - 0s 33ms/step


[[ 2.3006e-12  1.2845e-11  2.7819e-11  3.4609e-20    0.001702     0.96309    0.035211]]
5


0: 352x640 1 person, 672.2ms
Speed: 1.0ms preprocess, 672.2ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 28ms/step
[[ 3.7616e-12  3.8545e-11  2.4263e-11  4.8803e-20   0.0014139     0.97773    0.020857]]
5
1/1 [==============================] - 0s 31ms/step
[[ 3.7616e-12  3.8545e-11  2.4263e-11  4.8803e-20   0.0014139     0.97773    0.020857]]
5
1/1 [==============================] - 0s 29ms/step
[[ 3.7616e-12  3.8545e-11  2.4263e-11  4.8803e-20   0.0014139     0.97773    0.020857]]
5
1/1 [==============================] - 0s 20ms/step
[[ 3.7616e-12  3.8545e-11  2.4263e-11  4.8803e-20   0.0014139     0.97773    0.020857]]
5



0: 352x640 1 person, 702.2ms
Speed: 1.0ms preprocess, 702.2ms inference, 3.8ms postprocess per image at shape (1, 3, 640, 640)


1/1 [==============================] - 0s 20ms/step
[[ 7.4387e-12  3.3969e-11  2.2001e-11  2.6358e-20  0.00076095     0.97979    0.019452]]
5
1/1 [==============================] - 0s 27ms/step
[[ 7.4387e-12  3.3969e-11  2.2001e-11  2.6358e-20  0.00076095     0.97979    0.019452]]
5
1/1 [==============================] - 0s 21ms/step
[[ 7.4387e-12  3.3969e-11  2.2001e-11  2.6358e-20  0.00076095     0.97979    0.019452]]
5
1/1 [==============================] - 0s 20ms/step
[[ 7.4387e-12  3.3969e-11  2.2001e-11  2.6358e-20  0.00076095     0.97979    0.019452]]
5
